notifications:
  - webhook_url: "${SLACK_WEBHOOK_URL}"
    schedule:
      name: "weekly"
      description: "every Monday at 9:00"
      cron: "0 9 * * 1"
    metrics:
      - name: "frequency"
        description: "deployments frequency"
        query:
          filepath: "query/frequency.sql"