version: '3.8'
services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    env_file:
      - .env
    environment:
      - GO_ENV
    volumes:
      - .:/go/src/app
      # - ../setting/sample.yaml:/go/src/app/internal/setting/files/setting.yaml
      # - ../query/sample.sql:/go/src/app/internal/query/files/sample.sql
    working_dir: /go/src/app
