name: terraform-apply-all

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - setting.yaml
  workflow_dispatch:

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.2.4
          terraform_wrapper: false
      - name: Apply
        working-directory: ./terraform/
        run: make apply-all