name: check-setting

on:
  pull_request:
    paths:
      - setting.yaml

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: update github actions
        uses: vmware-tanzu/carvel-setup-action@v1
        run: |
          make update-github-actions
      - name: check
        run: |
          if ! git diff --exit-code --quiet
          then
            echo "prease run `make update-github-actions` command"
          fi
