name: deploy
"on":
  push:
    branches:
    - main
  workflow_dispatch: ""
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        install_components: beta
    - name: build and push
      id: build_push
      uses: ./.github/actions/build_push_image
      with:
        image_url: gcr.io/slack_notifiation/slack-notification-notification
        dockerfile_path: ./app/docker/Dockerfile
        build_path: .
    - name: update cloud run job of weekly
      uses: ./.github/actions/update_cloudrunjob
      with:
        jobname: slack-notification-weekly
        project: slack_notifiation
        region: asia-northeast1
