#@ load("@ytt:data", "data")
---
name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          install_components: "beta"

      - name: build and push
        id: build_push
        uses: ./.github/actions/build_push_image
        with:
          image_url: #@ 'gcr.io/' + data.values.terraform.project + "/" + data.values.terraform.common_prefix + 'notification'
          dockerfile_path: "./app/docker/Dockerfile"
          build_path: "."

      #@ for i in range(len(data.values.schedules)):
      - name: #@ "update cloud run job of " + data.values.schedules[i].name
        uses: ./.github/actions/update_cloudrunjob
        with:
          jobname: #@ data.values.terraform.common_prefix + data.values.schedules[i].name
          project: #@ data.values.terraform.project
          region:  #@ data.values.terraform.region
      #@ end
